name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Clean install
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force
          npm install -g npm@latest
          npm install
          npm install vite@4.5.2 --save-dev
        
      - name: Build
        run: |
          npm run build
          cp -r public/* dist/
          touch dist/.nojekyll
        env:
          NODE_ENV: production
          VITE_BASE_URL: /ee-portfolio/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 