name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Clean npm cache
        run: npm cache clean --force
          
      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install typescript@5.3.3 vite@5.0.12 @tanstack/react-query@5.17.19 next-themes@0.2.1 sonner@1.4.0 @radix-ui/react-toast@1.1.5 @radix-ui/react-aspect-ratio@1.0.3 @radix-ui/react-tooltip@1.0.7 @radix-ui/react-slot@1.0.2 @radix-ui/react-label@2.0.2 @radix-ui/react-dialog@1.0.5 @radix-ui/react-dropdown-menu@2.0.6 @radix-ui/react-avatar@1.0.4 react-type-animation tailwindcss-animate react-router@6.22.1 lucide-react@0.331.0 class-variance-authority@0.7.0 tailwind-merge@2.2.1 clsx@2.1.0 --legacy-peer-deps
        
      - name: Build
        run: |
          npm run build
          cp -r public/* dist/
          touch dist/.nojekyll
        env:
          NODE_ENV: production
          VITE_BASE_URL: /ee-portfolio/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 